### ISSUE TITLE
It will be pretty awesome if you include image output of for each PDF sample on your page. That will helps a lot lot. 

### ISSUE THREAD

**Issue by yesadahmed** [VahidN/PdfReport#12]
# Summary of the issue

## Environment

```
The in-use version:
Operating system: 
IDE: (e.g. Visual Studio 2015)
```

## Example code/Steps to reproduce:

```
paste your core code
```

## Output:

```
Exception message:
Full Stack trace:
```

**Comment by VahidN** [comment]
It has a samples browser. [You can find it here](https://github.com/VahidN/PdfReport/tree/master/Samples/DemosBrowser).
