### ISSUE TITLE
Infinite loop in PdfReport and FlushInBrowser

### ISSUE THREAD

**Issue by hamedmaleki1366** [VahidN/PdfReport#2]
hi all.

in PdfReport().Generate function 
i have below code that works : 

`var fileName = string.Format("{0}-rpt.pdf", Guid.NewGuid().ToString("N"));
                    fileName = HttpUtility.UrlEncode(fileName, Encoding.UTF8);
data.AsPdfFile(HttpContext.Current.Server.MapPath("~/Content/Temp/") + fileName);`

but when i flush data to browser program goes to infinite loop :
                    `data.FlushInBrowser(fileName, FlushType.Inline);`

what`s wrong?

both codes work on localhost but on the server only top code works.

**Comment by VahidN** [comment]
Probably you have an internal server error some where. [Use ELMAH](http://www.dotnettips.info/search?term=elmah) to log errors and exceptions on the server.
