### ISSUE TITLE
Passing image as parameter to XML Form document

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/PdfReport#3]
I am using [AcroFormTemplatePdfReport](https://github.com/VahidN/PdfReport/blob/master/Samples/PdfReportSamples/AcroFormTemplate/AcroFormTemplatePdfReport.cs), it works as expected, but I also need to pass some image(s) as parameter to the template. I looked at the toolbar on OpenOffice, it only has image button which actually is a button not an image. Is there a workaround for it?

**PS**: I also tried [XHtmlHeader](https://github.com/VahidN/PdfReport/blob/master/Samples/PdfReportSamples/HtmlHeader/HtmlHeaderPdfReport.cs#L62) but the problem with this approach is that, it scales down the main template.

One more thing: PdfReport is really great! thanks 👍👍👍

**Comment by VahidN** [comment]
[This post should work](https://stackoverflow.com/a/16056852/298573).

**Comment by SirwanAfifi** [comment]
Thanks man!
