### ISSUE TITLE
Genereate Excel and CSV file,

### ISSUE THREAD

**Issue by jagadeesh1492** [VahidN/PdfReport#4]
# Summary of the issue

Generate Excel,CSV File using this libiary

**Comment by VahidN** [comment]
This library creates Excel and CSV files and then embeds them in the .pdf file as attachments. It won't create them separately. [This is a sample which demonstrates this capability](https://github.com/VahidN/PdfReport/blob/master/Samples/PdfReportSamples/IList/IListPdfReport.cs#L154).
