### ISSUE TITLE
[Question] How can remove space between cell and HtmlTablecell template

### ISSUE THREAD

**Issue by molaie** [VahidN/PdfReport#7]
How can i remove extra space between a cell and html genereated cell? 
view attached image.

tried this code, but nothing happens:

    				 columns.AddColumn(column => {
					 column.PropertyName("User");
					 column.CellsHorizontalAlignment(HorizontalAlignment.Center);
					 column.IsVisible(true);
					 column.Order(1);
					 column.Width(3);
					 column.HeaderCell("User");
					 column.CalculatedField(list =>
					 {
						 var user = list.GetSafeStringValueOf("User");
						 var photo = list.GetSafeStringValueOf("Photo");
						 var image = string.Format("<img src='{0}' />", photo);
						 return
								@"<table style='width: 100%; font-size:9pt; border: 1px solid khaki; border-collapse: collapse;'>
												<tr>
													<td align='center' style='border: 1px solid khaki; border-collapse: collapse;'>" + user + @"</td>
												</tr>
												<tr>
													<td align='center' style='border: 1px solid khaki; border-collapse: collapse;'>" + image + @"</td>
												</tr>
									   </table>
									 ";
					 });
					 column.ColumnItemsTemplate(template =>
					 {
						 template.XHtml();
                                                 //added this, but no sucess.
						 template.BasicProperties(new CellBasicProperties {
							 CellPadding = 0f,
							 PaddingBottom = 0f,
							 PaddingTop = 0f
						 });
					 });
				 });

![image](https://user-images.githubusercontent.com/505055/53896529-6dc61880-4049-11e9-8662-95c9830d72c9.png)

**Comment by molaie** [comment]
Any idea or sample?

**Comment by VahidN** [comment]
- It doesn't apply zero values, because it makes all of the reports very ugly!
- If you don't like its defaults, create [a new XHtmlField](https://github.com/VahidN/PdfReport/blob/master/Lib/ColumnsItemsTemplates/XHtmlField.cs#L72) and then apply your custom formatting to the final returned `cell`. To use this new custom class, try 
```csharp
column.ColumnItemsTemplate(template =>
{
    template.CustomTemplate(new MyCustomXHtml());
    //template.XHtml();
});
```
