### ISSUE TITLE
Overall Summary Text is missing in new verion

### ISSUE THREAD

**Issue by MehdiSaeedifar** [VahidN/PdfReport#8]
Overall Summary Text is missing in the version 2.9.3.
The attached image taken from WebAppTests sample.
![bug](https://user-images.githubusercontent.com/10070897/54068296-9a07b200-4260-11e9-86f9-ca6ae4b66a43.JPG)

**Comment by VahidN** [comment]
Fixed it via #https://github.com/VahidN/PdfReport/commit/ecfcddfc7c57109745a97ea170b7414984a48dfc
