### ISSUE TITLE
Limit columns in maintable

### ISSUE THREAD

**Issue by FrancisEmpleo** [VahidN/PdfReport#9]
I want to limit the number of columns in the main table. Lets say the table will have 10 columns and then the limit will be 5, the first 5 columns will be in the first page and the second 5 columns will be on the next page. Is this doable?

**Comment by VahidN** [comment]
No. It's not possible. But if you have a larger number of columns, change the [doc.Orientation](https://github.com/VahidN/PdfReport/blob/master/Samples/PdfReportSamples/IList/IListPdfReport.cs#L16).
